### ISSUE TITLE
Errors with the source files should be available in the target directory

### ISSUE THREAD

**Issue by petterreinholdtsen** [unioslo/tsdfx#22]
When files with illegal file names or invalid ownership is present in the source directory, the problems
should be reported in a way available for those with access to the target directory, to allow people
to figure out why a copying is not taking place.

**Comment by abdulrahmanazab** [comment]
Discussed with Gard. He thinks that there should be one error.log file per destination directory. I think this is ok in order to avoid having a crowd of log files. Do you agree? 
If yes, I can start implementing

**Comment by petterreinholdtsen** [comment]
Yes, I agree.  But if it is easier to implement some other scheme, I suspect it is better to do it in a simple way.

**Comment by petterreinholdtsen** [comment]
I'm working on this now.  My proposal is to create a log queue with timeouts (ie only remember the errors newer than X seconds), and collect messages in the master process via stderr from the copier and scanner process, and write out the log file every time a new log message arrive.

I am working on a draft implementation now.

**Comment by petterreinholdtsen** [comment]
This issue was fixed when pull request #77 was merged.  Here is a draft text to put in the documentation:

Some errors are written into the destination directory, in a file named tsdfx-errors.log, to make the error message visible to the users.  This file will contain the most recent errors detected for a given set of source-destination directories, and is updated every time a new error is detected.

Typical errors reported here are files with names containing invalid characters, files with invalid file permissions, symlinks and dot files.  Such errors should be fixed in the source directory for the copying to take place.

The tsdfx-errors.log file can be safely removed, as it will be recreated when a new error is detected.
