### ISSUE TITLE
Copying fail some times for large files.

### ISSUE THREAD

**Issue by petterreinholdtsen** [unioslo/tsdfx#33]
Users report that some files fail to copy correctly.  Some report incorrect md5sum after transfer,
while others report that 'tar -ztvf' report that the file is corrupted.  UiO RT ticket #1970773 is one such user report, where  a 74 GiB file was corrected.  cmp reported byte differences in byte 5,368,381,441, where the source had byte value 1, and the destination had byte value 0.

The problem do not seem to happen with smaller files, and is not discovered by our test suite.

**Comment by dag-erling** [comment]
Is the size different as well?

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> Is the size different as well?

The size and timestamp of the two files were the same.

## 

Happy hacking
Petter Reinholdtsen

**Comment by dag-erling** [comment]
Can you get a binary diff? I think [bsdiff](http://www.daemonology.net/bsdiff/) is available in EPEL for RHEL6, and if not, it should be trivial to build.

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> Can you get a binary diff? I think
> [bsdiff](http://www.daemonology.net/bsdiff/) is available in EPEL for
> RHEL6, and if not, it should be trivial to build.

Yes.  I got a copy of both files stashed away and had plans to track
down a good binary diff capable of handling 74 GiB files.  I'll check
out bsdiff in RHEL6.

## 

Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Petter Reinholdtsen]

> I'll check out bsdiff in RHEL6.

bsdiff proved useless.  It fail with "Cannot allocate memory" when I try
to use it, and the manual page states "bsdiff uses memory equal to 17
times the size of 'oldfile', and requires an absolute minimum working
set size of 8 times the size of oldfile."

## 

Happy hacking
Petter Reinholdtsen

**Comment by dag-erling** [comment]
From your p70 example, it looks like an entire 64 kB block was zeroed in the output. This is
1. a round number
2. much less than the tsdfx copier's block size
3. equal to or a multiple of the underlying filesystem's block size
4. equal to OpenSSH's default buffer size

That and the fact that it only happens with large files (we should check, but I assume that the copier tasks start while the file is still being uploaded, which is rarely the case for smaller files) point to an external source. There is most likely a very small window during which the source file has a block of zeroes (most likely a gap resulting from an upwards `ftruncate(2)`) which the copier reads and copies, before that block is filled with data.

Unfortunately, this is all speculation unless we can find a reliable way to reproduce the issue in a test environment.

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> Unfortunately, this is all speculation unless we can find a reliable
> way to reproduce the issue in a test environment.

Yeah.  No idea how to test what is going on here. :(

But what if we change the logic of the code to not copy the last block
unless the file have not changed for a while?  This would make sure the
last block is read several times, but also would ensure it is only used
when no changes have happened at the end of the file for a few seconds.

It should reduce the risk of temporary trailing zeros to end up in the
destination file, at least.  Another idea is to try to detect holes in
the file and delay copying if some holes are discovered.  Is there a way
to detect a hole in a file, except just looking for sequences of null
bytes?

This patch implement what I have in mind:

diff --git a/libexec/copier/copier.c b/libexec/copier/copier.c
index 2dbda46..5895953 100644
--- a/libexec/copier/copier.c
+++ b/libexec/copier/copier.c
@@ -48,6 +48,7 @@
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
+#include <time.h>
 #include <unistd.h>

 #include <tsd/assert.h>
@@ -496,12 +497,18 @@ tsdfx_copier(const char *srcfn, const char *dstfn)
        if (copyfile_refresh(src) != 0 || copyfile_read(src) != 0 ||
            copyfile_refresh(dst) != 0 || copyfile_read(dst) != 0)
            goto fail;
+
-       /\* If the file changes the last few seconds and we ran
-          out of source file to read, wait a bit to see if it
-          keeps growing */
-       if (src->buflen < src->bufsize &&
-           MAX_RETRIES/(2*10) < (src->st.st_mtime - time(NULL)) &&
-           retries++ < MAX_RETRIES) {
-           usleep(100 \* 1000);
-           continue;
-       }
  +
      if (src->buflen == 0) {
-           /\* wait a bit to see if it keeps growing */
-           if (retries++ < MAX_RETRIES) {
-               usleep(100 \* 1000);
-               continue;
-           }
          /\* end of source file */
          copyfile_copystat(src, dst);
          if (copyfile_finish(src) != 0 ||

## 

Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Petter Reinholdtsen]

> Is there a way to detect a hole in a file, except just looking for
> sequences of null bytes?

I tracked down <URL: http://lwn.net/Articles/260795/ > documenting
different options.  I suspect we want to use lseek whence options
SEEK_HOLE to detect if there is a hole in the block we are reading.

## 

Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
I guess we can do something like this to refuse to read a block with
holes in it.  The cost is three lseek() for every read, but given our
large buffer size, this might be worth it.

diff --git a/libexec/copier/copier.c b/libexec/copier/copier.c
index 2dbda46..6ed5d3a 100644
--- a/libexec/copier/copier.c
+++ b/libexec/copier/copier.c
@@ -231,9 +232,29 @@ static int
 copyfile_read(struct copyfile *cf)
 {
    ssize_t rlen;
-   off_t currpos, nexthole;
  
  if (copyfile_isdir(cf))
      return (-1);
  +
-   /\* Detect holes and refuse to read if there are holes in the next block */
-   if ((currpos = lseek(cf->fd, 0, SEEK_CUR)) == (off_t)-1) {
-       ERROR("%s: read() unable to locate current position %s",
-             cf->name, strerror(errno));
-   }
-   nexthole = lseek(cf->fd, 0, SEEK_HOLE);
-   if (nexthole != (off_t)-1 &&
-       nexthole != cf->st.st_size &&
-       (nexthole -  currpos) < (off_t)cf->bufsize) {
-       ERROR("%s: read() found a hole in the file at position %d",
-             cf->name, nexthole);
-       return (-1);
-   }
-   if (lseek(cf->fd, currpos, SEEK_SET) != currpos) {
-       ERROR("%s: read() unable to set seek position: %s",
-             cf->name, strerror(errno));
-   }
  +
  if ((rlen = read(cf->fd, cf->buf, cf->bufsize)) < 0) {
      ERROR("%s: read(): %s", cf->name, strerror(errno));
      return (-1);

Do you have any better idea?  Both the last two patches passes the test
suite.  They even can work together, but I doubt that make sense.

## 

Happy hacking
Petter Reinholdtsen

**Comment by dag-erling** [comment]
[Petter Reinholdtsen]

> But what if we change the logic of the code to not copy the last block unless the file have not changed for a while? This would make sure the last block is read several times, but also would ensure it is only used when no changes have happened at the end of the file for a few seconds.

Pretty much what I suggested when I first became aware of the issue... but I think the `SEEK_HOLE` hack is a better solution overall _if_ the block of zeroes really is a hole.

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> Pretty much what I suggested when I first became aware of the
> issue... but I think the `SEEK_HOLE` hack is a better solution overall
> _if_ the block of zeroes really is a hole.

Yeah.  Not sure how to figure that out.

But we have a user her that is able to reproduce the problem.  On
request, he uploaded a 3.2 GiB file 10 times, and 4 of the files were
corrupted:

5/MINICPAN.tar.gz /tsd/p11/fx/import/something/5/MINICPAN.tar.gz differ: byte 3003056129, line 11432004
6/MINICPAN.tar.gz /tsd/p11/fx/import/something/6/MINICPAN.tar.gz differ: byte 1974796289, line 7508619
7/MINICPAN.tar.gz /tsd/p11/fx/import/something/7/MINICPAN.tar.gz differ: byte 3021012993, line 11496892
9/MINICPAN.tar.gz /tsd/p11/fx/import/something/9/MINICPAN.tar.gz differ: byte 3052797953, line 11618011

This mean we can implement the SEEK_HOLE change and see if things
improve for him.

## 

Happy hacking
Petter Reinholdtsen

**Comment by dag-erling** [comment]
[Petter Reinholdtsen]

> But we have a user her that is able to reproduce the problem. [...] This mean we can implement the SEEK_HOLE change and see if things improve for him.

That's great! Do you have a branch ready to review / pull?

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> That's great! Do you have a branch ready to review / pull?

I got a draft implementation, see pull request #39.  I'm not sure
exactly what we want to do if we meet a hole in the file.  The current
draft exits the copier and let it try again later with a new copier
process.  Perhaps it is better to wait a bit and try again in the same
process?

## 

Happy hacking
Petter Reinholdtsen

**Comment by dag-erling** [comment]
We should definitely try again in the same process, otherwise we will keep starting over from zero every time we hit a hole. But if the hole isn't filled after a certain amount of time (10 seconds perhaps?) then we should log an error and exit.

This reminds me that we should always log the sha1 digest of the destination file before we exit, even if we encountered an error.

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> We should definitely try again in the same process, otherwise we will
> keep starting over from zero every time we hit a hole. But if the hole
> isn't filled after a certain amount of time (10 seconds perhaps?) then
> we should log an error and exit.

I implemented this now.  Please have a look.

> This reminds me that we should always log the sha1 digest of the
> destination file before we exit, even if we encountered an error.

Something for a new github issue?

## 

Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
I've been working on adding hole detectoin using ioctl/FIEMAP in
addition to the lseek(SEEK_HOLE) method already implemented, because
RHEL6 do not have the lseek() support we need.  But according to
<URL: http://lwn.net/Articles/429345/ >, this might not really work, as
there are bugs in ext4 breaking FIEMAP hole detection that might have
made it into linux 2.6.38, and the RHEL6 machine in question is using
versoin 3.6.32-504.23.4.  I guess we need to check if that fix really is
in RHEL6.

The reason I started checking the FIEMAP support on Linux was that I am
unable to detect any holes when I test the ioctl call.  Not yet sure
why, but thought it best to give a heads up about the kernel version
issue.

## 

Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
I believe pull request #56 solved this issue.
