### ISSUE TITLE
Reload breaks copying

### ISSUE THREAD

**Issue by dag-erling** [unioslo/tsdfx#69]
Since some time around #63, a map reload seems to clear the `srcpath` / `dstpath` fields in `struct map`. The scan tasks know what to scan, but `tsdfx_copy_wrap()` gets blank source and destination directories and fails to copy anything. Everything works as expected until the first reload. Note that #68 fixed a bug that caused a reload to happen immediately on startup.

**Comment by dag-erling** [comment]
I found the bug. During a reload, when a task is unchanged from the old map to the new map, the scan task is moved to the new `struct map`. However, scan tasks now have a back-reference to their parent `struct map` so they can invoke `tsdfx_map_process()`. After `tsdfx_map_reload()`, this back-reference points to freed memory, so `tsdfx_map_process()` is working with garbage. The fix is to retain the entire `struct map` so the back-reference remains valid. I have a patch, but need to figure out a reliable way to reproduce the bug so we can test it properly.

**Comment by dag-erling** [comment]
See #72.

**Comment by petterreinholdtsen** [comment]
This issue was fixed when merging pull request #72.
