### ISSUE TITLE
Daemon stop scanning when source directory disappears temporarily

### ISSUE THREAD

**Issue by petterreinholdtsen** [unioslo/tsdfx#74]
When scanning source directories, and the directory is temporarely unavailable, the tsdfx scan code flag the scanner as broken and never try again to scan that directory.  This causes problem when the source directory is NFS mounted and the NFS server is unavailable temporarily.

We ran into this problem yesterday.  A restart solved it, but I suspect it would be better to try again later instead of giving up permanently.

**Comment by dag-erling** [comment]
In `tsdfx_scan_reset()`, if the directory has disappeared, the scan task's state is set to `TASK_INVALID`. Tasks in that state are never restarted. We need to modify `tsdfx_scan_sched()` to periodically reschedule invalid tasks, possibly at longer intervals than the normal scan interval.
